import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    if (typeof window !== 'undefined') {
        console.log(localStorage.getItem('theme'))
    }
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='current-background'>
        <div className='current-background_circle'></div>
      </div>
      {children}</body>
    </html>
  );
}
